language: node_js
node_js:
  - node
install:
  - npm install
script:
  - npm test
  - npm build
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: "build"
  github_token: $GITHUB_TOKEN
  on:
    branch: master